def projects = [
  [name: 'chedoparti-react-app', remote: 'https://github.com/martinianod/chedoparti-react-app.git'],
  [name: 'maria-belen-labarque-ceramic', remote: 'https://github.com/martinianod/maria-belen-labarque-ceramic.git'],
  [name: 'sistema-dietetica', remote: 'https://github.com/martinianod/sistema_dietetica.git'],
  [name: 'giftfinder-proyect', remote: 'https://github.com/martinianod/giftfinder-proyect.git']
  // panorama-mercados is not a Git repo in the local workspace yet. Register origin before enabling a Jenkins multibranch job.
].findAll { it.remote }

projects.each { project ->
  multibranchPipelineJob(project.name) {
    displayName(project.name)
    description("""
      Multibranch pipeline generated by Engineering Control Center.

      Required in the target repository:
      - Jenkinsfile at repo root.
      - Branch pushed to remote.
      - Docker build/publish stages defined by the Jenkinsfile.

      Local Jenkins cannot receive GitHub webhooks unless it is exposed through HTTPS.
      This job polls and scans branches every 5 minutes as the local-safe default.
    """.stripIndent().trim())
    branchSources {
      git {
        id("git-${project.name}")
        remote(project.remote)
        includes('*')
      }
    }
    factory {
      workflowBranchProjectFactory {
        scriptPath('Jenkinsfile')
      }
    }
    orphanedItemStrategy {
      discardOldItems {
        daysToKeep(14)
        numToKeep(20)
      }
    }
    triggers {
      periodicFolderTrigger {
        interval('5m')
      }
    }
  }
}
